### ISSUE TITLE
audio input does not work in safari on iOS/ipadOS 13.4

### ISSUE THREAD

**Issue by wfel** [K024/bangbangboom-editor#1]
https://github.com/K024/bangbangboom-editor/blob/d750c4ecba2ab1ea34792de69d588741e89003ba/src/MappingPage/Pages/MetaPage/Inputs.tsx#L52
iOS/ipadOS 13.4 does not support the MIMEType `audio/*` as the value of attribute `accept` (due to an unknow bug?) `.mp3,.wav,.aac,.m4a,.opus` could be used as a workaround until the bug has been fixed.

Reproduction code:
```html
<!doctype html>
<body>
    <input type="file" accept=".mp3,.wav,.aac,.m4a,.opus">
    <input type="file" accept="audio/*">
    <input type="file">
    <input type="text" id="t-input">
    <script>
        document.querySelector('#t-input').addEventListener('click',function(){
            let i = document.createElement('input')
            i.type='file'
            //i.accept='.mp3,.wav,.aac,.m4a'
            i.accept='audio/*'
            i.click();
        })
    </script>
</body>
```
---

Also, using `<input type="file" accept="..." onchange="..."` would be more readable and more robust than using a TextField while attach a event on it to trigger another `<input>`.
https://github.com/K024/bangbangboom-editor/blob/d750c4ecba2ab1ea34792de69d588741e89003ba/src/Common/Components/FileField.tsx#L40

**Comment by K024** [comment]
I'm sorry for not replying quickly. But a problem is that the interaction part of the editor is strongly bound to mouse gestures, and no touch screen support currently. Another problem is that the dependency bangbangboom-game hasn't specified a version, and the newest tag will conflict with packages.lock.json, and more bugs in that repo 😢. I'm also considering to migrate to immerjs for map state tracing. 
But the biggest problem is that I'm busy with my courses. I'll take a look at all the things when I have time. Sorry for that.
